version: '3'
services:
  mongo_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dfdb
    ports:
      - 11111:27017
    volumes:
      - mongo_data:/data/db
      - ./dbs/mongo:/docker-entrypoint-initdb.d
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 11112:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbs/mysql:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
  server:
    image: node
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm i ; npm start"
    depends_on:
      - mongo_db
      - mysql_db
    ports:
      - 11113:3000
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - client_angular_cache:/app/.angular/
      - client_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm i ; npm start"
    depends_on:
      - server
    ports:
      - 11114:4200
volumes:
  mysql_data:
  mongo_data:
  client_angular_cache:
  client_node_modules:
  server_node_modules:
